# Generated by Django 5.1.3 on 2024-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_post',
            name='ghjk',
        ),
    ]
