# Generated by Django 5.1.3 on 2024-12-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_box', '0003_categories_catcolor_categories_catcreated_and_more'),
        ('web_user', '0002_remove_web_post_ghjk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='web_user.web_users'),
        ),
        migrations.AlterField(
            model_name='web_post',
            name='post_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='admin_box.categories'),
        ),
    ]
