# Generated by Django 5.1.4 on 2025-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_post',
            name='post_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
