# Generated by Django 5.1.4 on 2025-01-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='web_user.web_users'),
        ),
    ]
