# Generated by Django 5.1.4 on 2025-01-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_user', '0009_alter_notification_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_notifications', to='web_user.web_users'),
        ),
    ]
