# Generated by Django 5.1.3 on 2024-12-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_box', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
