# Generated by Django 5.1.4 on 2024-12-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_box', '0002_rename_category_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='catColor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='catCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='catDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='catIcon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='catName',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='catSlug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
